#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cloudflared[-1]
	add ucitrack cloudflared
	set ucitrack.@cloudflared[-1].init=cloudflared
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
