#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

PROG=/usr/bin/cloudflared


section_enabled() {
	config_get_bool enabled "$1" 'enabled' 0
	[ $enabled -gt 0 ]
}
service_triggers() {
	procd_add_reload_trigger cloudflared
}
start_instance() {
	local cfg="$1"
	local port secret config_path
	local ARGS=""

	if ! section_enabled "$cfg"; then
		echo "disabled in config"
		return 1
	fi
	
	config_get free $cfg 'free'
	if [ "$free" == "1" ];  then
		ARGS="tunnel --logfile /tmp/cloudflared.info -url http://localhost:8080"
	else
		config_get token $cfg 'token'
		ARGS="tunnel --logfile /tmp/cloudflared.info run --token $token"
	fi

	procd_open_instance
	procd_set_param command $PROG $ARGS
	procd_set_param stderr 1
	procd_close_instance
	
	 
}

start_service() {
	config_load 'cloudflared'
	config_foreach start_instance 'cloudflared'
}

stop_instance() {  
	local cfg="$1"

	
}

stop_service() {
	config_load 'cloudflared'
	config_foreach stop_instance 'cloudflared'
}

